[package]
name = "fuzzcheck_mutators"
version = "0.1.0"
authors = ["Lo√Øc Lecrenier <loic.lecrenier@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.7", features = ["small_rng"] }
fuzzcheck = { path = "../fuzzcheck" }
